---
title: "Hot or Not?"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(tidyverse)
library(zoo)
```


```{r}
skater_games <- read_csv("../../data/skater_games.csv")

p <- "Kopitar"

# calculate rolling averages for player
player <- skater_games %>%
  add_fantasy_points() %>%
  filter(str_detect(player, p)) %>%
  arrange(date) %>%
  mutate(rolling = rollmean(f_points, 10, fill = NA, align = "right")) %>%
  arrange(desc(date)) %>%
  mutate(i = row_number() * -1)


# calculate historic quantiles
stats <- player %>%
  summarise(max = max(rolling, na.rm = T),
            min = min(rolling, na.rm = T),
            mid = median(rolling, na.rm = T),
            q25 = quantile(rolling, .25, na.rm = T),
            q75 = quantile(rolling, .75, na.rm = T))

# plot
player %>%
  ggplot(aes(x = i, y = rolling)) +
    geom_point(data = head(player, 1), size = 3) +
    geom_point(alpha = .1) +
    geom_hline(aes(yintercept = stats$mid), linetype = "dashed") +
    coord_cartesian(ylim = c(0, round(stats$max) + 1), xlim = c(-100, 0)) +
    geom_smooth(method = "loess", se = F, span = .05, color = "black") +
    annotate("rect", xmin = -200, xmax = 0, ymin = stats$q25, ymax = stats$mid, alpha = .25, fill = "steelblue") +
    annotate("rect", xmin = -200, xmax = 0, ymin = stats$min, ymax = stats$q25, alpha = .5, fill = "steelblue") +
    annotate("rect", xmin = -200, xmax = 0, ymin = stats$mid, ymax = stats$q75, alpha = .25, fill = "brown1") +
    annotate("rect", xmin = -200, xmax = 0, ymin = stats$q75, ymax = stats$max, alpha = .5, fill = "brown1") +
    scale_x_continuous(labels = abs) +
    scale_y_continuous(breaks = seq(-2, 10, 1)) +
    labs(title = str_c(unique(player$player), " - Hot or Not?"),
         subtitle = "10 game rolling avarage points production with historic quantiles",
         y = "Fantasy Points",
         x = "Games Ago") +
  theme_adhockey()
```

